---
name: docker

on:
  push:
    branches:
      - master
    paths:
      - VERSION
      - .github/workflows/docker.yml

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set version variable
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        id: docker-build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/dave:latest,ghcr.io/${{ github.repository_owner }}/dave:${{ env.VERSION }}

      - name: Image digest
        run: echo ${{ steps.docker-build.outputs.digest }}
